In [1]:
import keras

Using TensorFlow backend.


In [2]:
import numpy as np
import pandas as pd

In [4]:
dataset=pd.read_csv("D:\DATA SCIENCE\DATA SETS\Churn_Modelling.csv")

In [5]:
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [6]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

DATA PRE-PROCESSING


In [7]:
dataset.isnull().any()

RowNumber          False
CustomerId         False
Surname            False
CreditScore        False
Geography          False
Gender             False
Age                False
Tenure             False
Balance            False
NumOfProducts      False
HasCrCard          False
IsActiveMember     False
EstimatedSalary    False
Exited             False
dtype: bool

In [8]:
#Assigning the x and y values to the data

x=dataset.iloc[:,3:13].values

y=dataset.iloc[:,13].values

In [9]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [10]:
#since some data is in the categorical format we have to assign the values to it
#label encoding to the Gender

from sklearn.preprocessing import LabelEncoder

In [11]:
lb=LabelEncoder()

In [12]:
x[:,2]=lb.fit_transform(x[:,2])

In [13]:
#since the countries are in 3 level categorical data apply one hot encoding

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [14]:
ct = ColumnTransformer(transformers=[('oh', OneHotEncoder(),[1])], remainder='passthrough') 

x=ct.fit_transform(x)


In [15]:
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [16]:
#splitting the data

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [17]:
x_train

array([[1.0, 0.0, 0.0, ..., 0, 0, 188484.52],
       [1.0, 0.0, 0.0, ..., 1, 1, 159344.43],
       [1.0, 0.0, 0.0, ..., 1, 1, 85733.33],
       ...,
       [1.0, 0.0, 0.0, ..., 1, 0, 199390.45],
       [0.0, 1.0, 0.0, ..., 1, 1, 26106.39],
       [1.0, 0.0, 0.0, ..., 0, 0, 92223.59]], dtype=object)

In [18]:
#scaling the data

from sklearn.preprocessing import MinMaxScaler
Sc=MinMaxScaler()
x_train=Sc.fit_transform(x_train)
x_test=Sc.transform(x_test)

**BUILDING THE NN MODEL**

In [19]:
from keras.models import Sequential

In [20]:
from keras.layers import Dense

Initializing the NN model



In [21]:
model=Sequential()

Add input layer

In [22]:
model.add(Dense(input_dim=x_train.shape[1],kernel_initializer="random_uniform",activation="relu",units=6))

Add hidden layer

In [23]:
model.add(Dense(kernel_initializer="random_uniform",activation="relu",units=6))

Add outout layer

In [24]:
model.add(Dense(kernel_initializer="random_uniform",activation="sigmoid",units=1))

**COMPILING THE MODEL**

In [25]:
model.compile(loss="binary_crossentropy",optimizer="adam",metrics=["accuracy"])

In [26]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 6)                 78        
_________________________________________________________________
dense_2 (Dense)              (None, 6)                 42        
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 7         
Total params: 127
Trainable params: 127
Non-trainable params: 0
_________________________________________________________________


**TRAIN THE NN MODEL**

In [27]:
model.fit(x_train,y_train,epochs=50,batch_size=32)

Epoch 1/50
8000/8000 [==============================] - 1s 118us/step - loss: 0.5728 - accuracy: 0.7955
Epoch 2/50
8000/8000 [==============================] - 1s 66us/step - loss: 0.4869 - accuracy: 0.7971
Epoch 3/50
8000/8000 [==============================] - 1s 65us/step - loss: 0.4761 - accuracy: 0.7971
Epoch 4/50
8000/8000 [==============================] - 1s 73us/step - loss: 0.4678 - accuracy: 0.7971
Epoch 5/50
8000/8000 [==============================] - 1s 123us/step - loss: 0.4625 - accuracy: 0.7971
Epoch 6/50
8000/8000 [==============================] - 1s 120us/step - loss: 0.4578 - accuracy: 0.7971
Epoch 7/50
8000/8000 [==============================] - 1s 119us/step - loss: 0.4539 - accuracy: 0.7971
Epoch 8/50
8000/8000 [==============================] - 1s 128us/step - loss: 0.4503 - accuracy: 0.7971
Epoch 9/50
8000/8000 [==============================] - 1s 130us/step - loss: 0.4471 - accuracy: 0.7971
Epoch 10/50
8000/8000 [==============================] - 1s 129us/s

In [29]:
#prediction

y_pred=model.predict(x_test)
y_pred=y_pred>0.5

In [30]:
#Accuracy score
from sklearn.metrics import accuracy_score
print("Testing Accuracy Score:",accuracy_score(y_test,y_pred)*100,"%")

Testing Accuracy Score: 82.65 %


In [31]:
model.save("bankmodel.h5")

In [34]:
 import joblib

In [35]:
joblib.dump(Sc,"bank_scalar.save")

['bank_scalar.save']